# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np


#### 2. Print your NumPy version.

In [3]:
# your code here

print(np.__version__)

1.24.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
# Method 1

a = np.random.random((2, 3, 5))

print(a)

[[[0.19831435 0.71969521 0.33645323 0.33692401 0.41296732]
  [0.44086392 0.6121816  0.63820265 0.98995664 0.99689764]
  [0.44076293 0.2102771  0.93368093 0.73759726 0.13270902]]

 [[0.89610825 0.81949817 0.37781867 0.54970324 0.08338117]
  [0.56189131 0.49528455 0.96460688 0.5248241  0.06225194]
  [0.94232936 0.46446918 0.97153517 0.48584656 0.83588511]]]


In [11]:
# Method 2

array2 = np.random.randint(1, 100, size=(2, 3, 5))

print(array2)

[[[85 11 14 43 86]
  [55  8 21 40  2]
  [35 72  5 97 50]]

 [[48 28 67 96 19]
  [96 75 31 53 11]
  [86 25 72 23 92]]]


In [58]:
# Method 3

array3 = np.random.rand(2, 3, 5)

print(array3)

[[[0.46126959 0.40019702 0.7585145  0.70771275 0.08789665]
  [0.18323881 0.02131218 0.0308184  0.48737373 0.13423032]
  [0.01394632 0.62360157 0.96013001 0.77589664 0.09828046]]

 [[0.3732969  0.66389373 0.563034   0.81220325 0.87310626]
  [0.49382749 0.52195298 0.42627851 0.29308631 0.67150829]
  [0.09563758 0.96849758 0.13746949 0.84952666 0.71987519]]]


#### 4. Print *a*.


In [12]:
# your code here

print(a)

[[[0.19831435 0.71969521 0.33645323 0.33692401 0.41296732]
  [0.44086392 0.6121816  0.63820265 0.98995664 0.99689764]
  [0.44076293 0.2102771  0.93368093 0.73759726 0.13270902]]

 [[0.89610825 0.81949817 0.37781867 0.54970324 0.08338117]
  [0.56189131 0.49528455 0.96460688 0.5248241  0.06225194]
  [0.94232936 0.46446918 0.97153517 0.48584656 0.83588511]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [15]:
# your code here

b = np.ones((5, 2, 3))


#### 6. Print *b*.


In [16]:
# your code here

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [60]:
# your code here

'''
A y B pueden tener el mismo tamaño porque podemos reestructurar las matrices en python. 
Se puede tener la misma cantidad de valores y diferente estructura.
'''

a.size == b.size

print(nueva_b)

print('\n')

print(a)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


[[[0.19831435 0.71969521 0.33645323 0.33692401 0.41296732]
  [0.44086392 0.6121816  0.63820265 0.98995664 0.99689764]
  [0.44076293 0.2102771  0.93368093 0.73759726 0.13270902]]

 [[0.89610825 0.81949817 0.37781867 0.54970324 0.08338117]
  [0.56189131 0.49528455 0.96460688 0.5248241  0.06225194]
  [0.94232936 0.46446918 0.97153517 0.48584656 0.83588511]]]


#### 8. Are you able to add *a* and *b*? Why or why not?


In [28]:
# your answer here

'''
Los vectores a y b no se pueden sumar porque no tienen las mismas dimensiones.
'a' tiene estructura (2,3,5) y 'b' tiene estructura (5,2,3)
'''

"\nLos vectores a y b no se pueden sumar porque no tienen el mismo tamaño.\n'a' tiene estructura (2,3,5) y 'b' tiene estructura (5,2,3)\n"

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [61]:
# your code here

c = b.transpose(1,2,0)

print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [34]:
# your code/answer here

'''
Pueden sumarse porque ambas matrices tienen el mismo tamaño y estructura.
'''

d = a + c

print(d)

print('\n')

print(d.sum())

[[[1.19831435 1.71969521 1.33645323 1.33692401 1.41296732]
  [1.44086392 1.6121816  1.63820265 1.98995664 1.99689764]
  [1.44076293 1.2102771  1.93368093 1.73759726 1.13270902]]

 [[1.89610825 1.81949817 1.37781867 1.54970324 1.08338117]
  [1.56189131 1.49528455 1.96460688 1.5248241  1.06225194]
  [1.94232936 1.46446918 1.97153517 1.48584656 1.83588511]]]


47.17291744792977


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [35]:
# your code/answer here

'''
Los valores de 'd' son los valores de a + 1. 
'''

print(a)

print('\n')

print(d)

[[[0.19831435 0.71969521 0.33645323 0.33692401 0.41296732]
  [0.44086392 0.6121816  0.63820265 0.98995664 0.99689764]
  [0.44076293 0.2102771  0.93368093 0.73759726 0.13270902]]

 [[0.89610825 0.81949817 0.37781867 0.54970324 0.08338117]
  [0.56189131 0.49528455 0.96460688 0.5248241  0.06225194]
  [0.94232936 0.46446918 0.97153517 0.48584656 0.83588511]]]


[[[1.19831435 1.71969521 1.33645323 1.33692401 1.41296732]
  [1.44086392 1.6121816  1.63820265 1.98995664 1.99689764]
  [1.44076293 1.2102771  1.93368093 1.73759726 1.13270902]]

 [[1.89610825 1.81949817 1.37781867 1.54970324 1.08338117]
  [1.56189131 1.49528455 1.96460688 1.5248241  1.06225194]
  [1.94232936 1.46446918 1.97153517 1.48584656 1.83588511]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [36]:
# your code here

e = a * c

print(e)

[[[0.19831435 0.71969521 0.33645323 0.33692401 0.41296732]
  [0.44086392 0.6121816  0.63820265 0.98995664 0.99689764]
  [0.44076293 0.2102771  0.93368093 0.73759726 0.13270902]]

 [[0.89610825 0.81949817 0.37781867 0.54970324 0.08338117]
  [0.56189131 0.49528455 0.96460688 0.5248241  0.06225194]
  [0.94232936 0.46446918 0.97153517 0.48584656 0.83588511]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [62]:
# your code/answer here

'''
Si es igual. e = a*c
el cubo e y el cubo a tienen los mismos resultados.
'''

a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [40]:
# your code here

d_max = d.max()

d_min = d.min()

d_mean = np.median(d)

print (f'El máximo de d es: {d_max}. El minimo de d es: {d_min}. La moda de d es: {d_mean}')

El máximo de d es: 1.9968976424614424. El minimo de d es: 1.0622519421279288. La moda de d es: 1.5372636657338195


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [43]:
# your code here

f = np.empty((2, 3, 5))

f

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [51]:
# your code here

'''
for capa in range(f.shape[o]):  # 2 capas
    for fila in range(f.shape[1]):  # 3 filas
        for col in range(f.shape[2]):  # 5 columnas
            
            if d_min == d[capa][fila][col]:  # Si esta entre el minimo ponme 0 en f
                
                f[capa][fila][col] = 0
                
            elif
            
            elif
            
            
'''

f = np.where((d > d_min) & (d < d_mean), 25,
             np.where((d > d_mean) & (d < d_max), 75,
                      np.where(d == d_mean, 50,
                               np.where(d == d_min, 0,
                                        np.where(d == d_max, 100, 0)))))

print(f)

[[[ 25  75  25  25  25]
  [ 25  75  75  75 100]
  [ 25  25  75  75  25]]

 [[ 75  75  25  75  25]
  [ 75  25  75  25   0]
  [ 75  25  75  25  75]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [52]:
# your code here

print(d)
print('\n')
print(f)

[[[1.19831435 1.71969521 1.33645323 1.33692401 1.41296732]
  [1.44086392 1.6121816  1.63820265 1.98995664 1.99689764]
  [1.44076293 1.2102771  1.93368093 1.73759726 1.13270902]]

 [[1.89610825 1.81949817 1.37781867 1.54970324 1.08338117]
  [1.56189131 1.49528455 1.96460688 1.5248241  1.06225194]
  [1.94232936 1.46446918 1.97153517 1.48584656 1.83588511]]]


[[[ 25  75  25  25  25]
  [ 25  75  75  75 100]
  [ 25  25  75  75  25]]

 [[ 75  75  25  75  25]
  [ 75  25  75  25   0]
  [ 75  25  75  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [56]:
# your code here

g = np.where((f == 0) , 'A',
             np.where((f == 25), 'B',
                      np.where(f == 50, 'C',
                               np.where(f == 75, 'D',
                                        np.where(d == 100, 0, 'E')))))

print(g)

[[['B' 'D' 'B' 'B' 'B']
  ['B' 'D' 'D' 'D' 'E']
  ['B' 'B' 'D' 'D' 'B']]

 [['D' 'D' 'B' 'D' 'B']
  ['D' 'B' 'D' 'B' 'A']
  ['D' 'B' 'D' 'B' 'D']]]
