# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [7]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [8]:
# your code here
print(np.__version__)

1.26.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [9]:
# Method 1

a = np.random.random((2, 3, 5)) # 2 depth dimensions, 3 rows, 5 columns
print(a)

[[[0.93318069 0.05042614 0.44601816 0.56844454 0.07882009]
  [0.06988583 0.54968857 0.34879718 0.61756144 0.01234038]
  [0.27513101 0.59712302 0.18000027 0.77342939 0.61332288]]

 [[0.36506249 0.33199804 0.15172    0.58846996 0.70060608]
  [0.76572342 0.56419835 0.97935695 0.9487987  0.88092679]
  [0.88790228 0.4419418  0.25306438 0.97404839 0.74296607]]]


In [10]:
# Method 2
a1 = np.random.random((3,2,5)).reshape(2,3,5)
print(a1)


[[[0.82900488 0.73454109 0.91767468 0.96629992 0.62544855]
  [0.80737513 0.04714776 0.06245017 0.26429804 0.6526174 ]
  [0.96494927 0.81679881 0.23640714 0.64415859 0.53657613]]

 [[0.37376372 0.07995551 0.76796276 0.34934927 0.30742639]
  [0.56617799 0.51332824 0.9555252  0.58928808 0.97600237]
  [0.57446822 0.23507697 0.31005761 0.59423348 0.7736217 ]]]


In [11]:
# Method 3
a2 = np.random.random((5,2,3)).reshape(2,3,5)
print(a2)

[[[0.06791244 0.6865864  0.39587633 0.88760671 0.87620588]
  [0.68302119 0.68450638 0.60078347 0.21362471 0.6157816 ]
  [0.54889482 0.41129848 0.44356585 0.58988725 0.05337614]]

 [[0.92210398 0.16693163 0.95851295 0.09886761 0.67478257]
  [0.62741281 0.21297944 0.26068037 0.79865663 0.718061  ]
  [0.55381945 0.05636615 0.64570962 0.38136942 0.7146136 ]]]


#### 4. Print *a*.


In [12]:
# your code here
print(a)

[[[0.93318069 0.05042614 0.44601816 0.56844454 0.07882009]
  [0.06988583 0.54968857 0.34879718 0.61756144 0.01234038]
  [0.27513101 0.59712302 0.18000027 0.77342939 0.61332288]]

 [[0.36506249 0.33199804 0.15172    0.58846996 0.70060608]
  [0.76572342 0.56419835 0.97935695 0.9487987  0.88092679]
  [0.88790228 0.4419418  0.25306438 0.97404839 0.74296607]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [13]:
# your code here
b = np.ones((5,2,3))


#### 6. Print *b*.


In [14]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [15]:
# your code 
a.size

30

In [16]:
b.size # a and b have the same size but different shape 

30

#### 8. Are you able to add *a* and *b*? Why or why not?


In [17]:
# your answer here
a+b # a and b have different shapes so we can not sum them 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [18]:
# your code here
c = b.reshape((2,3,5))

In [19]:
c.shape

(2, 3, 5)

In [20]:
a.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [21]:
# your code/answer here
d = a+c # now a and c have the same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [22]:
# your code/answer here
print(a)

[[[0.93318069 0.05042614 0.44601816 0.56844454 0.07882009]
  [0.06988583 0.54968857 0.34879718 0.61756144 0.01234038]
  [0.27513101 0.59712302 0.18000027 0.77342939 0.61332288]]

 [[0.36506249 0.33199804 0.15172    0.58846996 0.70060608]
  [0.76572342 0.56419835 0.97935695 0.9487987  0.88092679]
  [0.88790228 0.4419418  0.25306438 0.97404839 0.74296607]]]


In [23]:
print(d) # the elements of d matriz are one more than the elements of a

[[[1.93318069 1.05042614 1.44601816 1.56844454 1.07882009]
  [1.06988583 1.54968857 1.34879718 1.61756144 1.01234038]
  [1.27513101 1.59712302 1.18000027 1.77342939 1.61332288]]

 [[1.36506249 1.33199804 1.15172    1.58846996 1.70060608]
  [1.76572342 1.56419835 1.97935695 1.9487987  1.88092679]
  [1.88790228 1.4419418  1.25306438 1.97404839 1.74296607]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [24]:
# your code here
e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [25]:
# your code/answer here
e.shape

(2, 3, 5)

In [26]:
a.shape # a and e have the same size and shape but the elements (value of the elements) of these arrays are not the same 

(2, 3, 5)

In [28]:
a is e

False

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [83]:
# your code here
d_max = d.max()
print(d_max)

1.9167252727209203


In [84]:
d_min = d.min()
print(d_min)

1.0179287901174003


In [86]:
d_mean = d.mean()
print(d_mean)

1.4971033974890786


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [110]:
# your code here
f = np.empty_like(d)
print(f)

[[[0.59114434 0.37944836 0.91626046 0.28495271 0.89749593]
  [0.15825395 0.78648961 0.90840195 0.3358441  0.50104904]
  [0.01792879 0.51269949 0.02067997 0.02399822 0.6121325 ]]

 [[0.44436133 0.52541945 0.65988746 0.08534969 0.64490226]
  [0.7655799  0.11094524 0.12047281 0.75611219 0.91672527]
  [0.81741014 0.81540404 0.05637857 0.7579681  0.48940603]]]


In [123]:
f1 = np.empty_like(d)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [120]:
for i, value_i in enumerate(d):
    for j, value_j in enumerate(value_i):
        for index, value in enumerate(value_j):
            if value > d_min and value < d_mean:
                value = 25
                f[i][j][index] = value
        
            if value > d_mean and value < d_max:
                value = 75
                f[i][j][index] = value
        
            if value == d_mean:
                value = 50
                f[i][j][index] = value
        
            if value == d_min:
                value = 0
                f[i][j][index] = value
        
            if value == d_max:
                value = 100
                f[i][j][index] = value
print(f)                

[[[ 75.  25.  75.  25.  75.]
  [ 25.  75.  75.  25.  75.]
  [  0.  75.  25.  25.  75.]]

 [[ 25.  75.  75.  25.  75.]
  [ 75.  25.  25.  75. 100.]
  [ 75.  75.  25.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [121]:
# your code here
print(d)

[[[1.59114434 1.37944836 1.91626046 1.28495271 1.89749593]
  [1.15825395 1.78648961 1.90840195 1.3358441  1.50104904]
  [1.01792879 1.51269949 1.02067997 1.02399822 1.6121325 ]]

 [[1.44436133 1.52541945 1.65988746 1.08534969 1.64490226]
  [1.7655799  1.11094524 1.12047281 1.75611219 1.91672527]
  [1.81741014 1.81540404 1.05637857 1.7579681  1.48940603]]]


In [122]:
print(f)

[[[ 75.  25.  75.  25.  75.]
  [ 25.  75.  75.  25.  75.]
  [  0.  75.  25.  25.  75.]]

 [[ 25.  75.  75.  25.  75.]
  [ 75.  25.  25.  75. 100.]
  [ 75.  75.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [140]:
# your code here
letras = np.where(f == 0, 'A', np.where (f == 25, 'B', np.where(f==50, 'C',np.where(f==75,'D', 'E'))))
print(letras)

[[['D' 'B' 'D' 'B' 'D']
  ['B' 'D' 'D' 'B' 'D']
  ['A' 'D' 'B' 'B' 'D']]

 [['B' 'D' 'D' 'B' 'D']
  ['D' 'B' 'B' 'D' 'E']
  ['D' 'D' 'B' 'D' 'B']]]
