# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# Importar NumPy como np (np es como vamos a nombrar NumPy)

import numpy as np

#### 2. Print your NumPy version.

In [3]:
# Printear mi versión de NumPy
print(np.__version__)

1.24.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [12]:
# Method 1: Mostrar 

a = np.random.random((2,3,5))

a

array([[[0.45641588, 0.1180306 , 0.8092422 , 0.5480323 , 0.36410259],
        [0.32136215, 0.47390696, 0.12298126, 0.59741572, 0.08756855],
        [0.86514556, 0.73705111, 0.51307075, 0.38413824, 0.74738241]],

       [[0.13914766, 0.16098711, 0.48123655, 0.63856963, 0.35812443],
        [0.87677307, 0.89945657, 0.41665061, 0.60677174, 0.15559353],
        [0.24799211, 0.90619313, 0.80791867, 0.81890647, 0.81931788]]])

In [6]:
# Method 2

dim3_2 = np.random.rand(2, 3, 5)
dim3_2

array([[[0.35179907, 0.24649957, 0.584869  , 0.98622945, 0.84902329],
        [0.1739593 , 0.63562866, 0.90222537, 0.67134865, 0.4990768 ],
        [0.68282112, 0.87336116, 0.29214292, 0.62389093, 0.67992775]],

       [[0.90086347, 0.27427973, 0.61326716, 0.71472822, 0.91395698],
        [0.64999036, 0.23907261, 0.56959787, 0.85186327, 0.61860522],
        [0.53317919, 0.58701729, 0.5471588 , 0.72440214, 0.41759209]]])

In [11]:
# Method 3
dim3_3 = np.random.random_sample((2, 3, 5))
dim3_3

array([[[0.77816106, 0.76671237, 0.42663678, 0.85117702, 0.67794171],
        [0.1563999 , 0.15447936, 0.12315593, 0.34094254, 0.69714873],
        [0.11776975, 0.62232498, 0.56112716, 0.52353835, 0.23896444]],

       [[0.49407232, 0.09806403, 0.2592525 , 0.94367705, 0.38670947],
        [0.61900608, 0.7584664 , 0.79883147, 0.97626545, 0.20860154],
        [0.42094087, 0.19368223, 0.03925736, 0.5965593 , 0.17996877]]])

#### 4. Print *a*.


In [13]:
a

array([[[0.45641588, 0.1180306 , 0.8092422 , 0.5480323 , 0.36410259],
        [0.32136215, 0.47390696, 0.12298126, 0.59741572, 0.08756855],
        [0.86514556, 0.73705111, 0.51307075, 0.38413824, 0.74738241]],

       [[0.13914766, 0.16098711, 0.48123655, 0.63856963, 0.35812443],
        [0.87677307, 0.89945657, 0.41665061, 0.60677174, 0.15559353],
        [0.24799211, 0.90619313, 0.80791867, 0.81890647, 0.81931788]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [15]:
dim = [5, 2, 3]
b = np.ones(dim)

#### 6. Print *b*.


In [16]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [17]:
a.size == b.size

True

In [18]:
a.size

30

In [19]:
b.size

30

#### 8. Are you able to add *a* and *b*? Why or why not?


In [20]:
a+b # No se puede sumar porque el tamaño de la matriz es diferente

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [27]:
c = b.transpose(1, 2, 0)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [28]:
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [30]:
d = a+c
d

array([[[1.45641588, 1.1180306 , 1.8092422 , 1.5480323 , 1.36410259],
        [1.32136215, 1.47390696, 1.12298126, 1.59741572, 1.08756855],
        [1.86514556, 1.73705111, 1.51307075, 1.38413824, 1.74738241]],

       [[1.13914766, 1.16098711, 1.48123655, 1.63856963, 1.35812443],
        [1.87677307, 1.89945657, 1.41665061, 1.60677174, 1.15559353],
        [1.24799211, 1.90619313, 1.80791867, 1.81890647, 1.81931788]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [36]:
print('MATRIZ A')
print(a)
print()
print()
print()
print('MATRIZ D') 
print(d)

MATRIZ A
[[[0.45641588 0.1180306  0.8092422  0.5480323  0.36410259]
  [0.32136215 0.47390696 0.12298126 0.59741572 0.08756855]
  [0.86514556 0.73705111 0.51307075 0.38413824 0.74738241]]

 [[0.13914766 0.16098711 0.48123655 0.63856963 0.35812443]
  [0.87677307 0.89945657 0.41665061 0.60677174 0.15559353]
  [0.24799211 0.90619313 0.80791867 0.81890647 0.81931788]]]



MATRIZ D
[[[1.45641588 1.1180306  1.8092422  1.5480323  1.36410259]
  [1.32136215 1.47390696 1.12298126 1.59741572 1.08756855]
  [1.86514556 1.73705111 1.51307075 1.38413824 1.74738241]]

 [[1.13914766 1.16098711 1.48123655 1.63856963 1.35812443]
  [1.87677307 1.89945657 1.41665061 1.60677174 1.15559353]
  [1.24799211 1.90619313 1.80791867 1.81890647 1.81931788]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [37]:
e = a*c
e

array([[[0.45641588, 0.1180306 , 0.8092422 , 0.5480323 , 0.36410259],
        [0.32136215, 0.47390696, 0.12298126, 0.59741572, 0.08756855],
        [0.86514556, 0.73705111, 0.51307075, 0.38413824, 0.74738241]],

       [[0.13914766, 0.16098711, 0.48123655, 0.63856963, 0.35812443],
        [0.87677307, 0.89945657, 0.41665061, 0.60677174, 0.15559353],
        [0.24799211, 0.90619313, 0.80791867, 0.81890647, 0.81931788]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [38]:
e==a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [44]:
d_max = d.max()
print(f'El valor máximo es {d_max}')
print()
d_min = d.min()
print(f'El valor máximo es {d_min}')
print()
d_mean = d.mean()
print(f'El valor medio es {d_mean}')

El valor máximo es 1.9061931335178182

El valor máximo es 1.0875685541231372

El valor medio es 1.5159828481395048


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [45]:
f = np.empty((2, 3, 5))
f

array([[[0.45641588, 0.1180306 , 0.8092422 , 0.5480323 , 0.36410259],
        [0.32136215, 0.47390696, 0.12298126, 0.59741572, 0.08756855],
        [0.86514556, 0.73705111, 0.51307075, 0.38413824, 0.74738241]],

       [[0.13914766, 0.16098711, 0.48123655, 0.63856963, 0.35812443],
        [0.87677307, 0.89945657, 0.41665061, 0.60677174, 0.15559353],
        [0.24799211, 0.90619313, 0.80791867, 0.81890647, 0.81931788]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [48]:
d.shape

(2, 3, 5)

In [49]:
f.shape

(2, 3, 5)

In [50]:
for capa in range(f.shape[0]):   # 2 capas
    
    for fila in range(f.shape[1]):   # 3 filas
        
        for col in range(f.shape[2]):  # 5 columnas
            
            
            if d_min == d[capa][fila][col]: # si es el minimo ponme cero en f
                
                f[capa][fila][col] = 0
                
            
            elif d_min < d[capa][fila][col] < d_mean: # si esta entre el minimo y la media ponme 25
                
                f[capa][fila][col] = 25
                
                
            elif d_mean == d[capa][fila][col]: # si es la media ponme 50 en f
                
                f[capa][fila][col] = 50
                
                
            elif d_mean < d[capa][fila][col] < d_max: # si esta entre la media y el maximo ponme 75
                
                f[capa][fila][col] = 75
                
                
            elif d_max == d[capa][fila][col]: # si es el maximo ponme 100 en f
                
                f[capa][fila][col] = 100
        

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [52]:
f

array([[[ 25.,  25.,  75.,  75.,  25.],
        [ 25.,  25.,  25.,  75.,   0.],
        [ 75.,  75.,  25.,  25.,  75.]],

       [[ 25.,  25.,  25.,  75.,  25.],
        [ 75.,  75.,  25.,  75.,  25.],
        [ 25., 100.,  75.,  75.,  75.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [53]:
f = f.astype('str')   # a formato string


for capa in range(f.shape[0]):   # 2 capas
    
    for fila in range(f.shape[1]):   # 3 filas
        
        for col in range(f.shape[2]):  # 5 columnas
            
            
            if d_min == d[capa][fila][col]: # si es el minimo ponme A en f
                
                f[capa][fila][col] = 'A'
                
            
            elif d_min < d[capa][fila][col] < d_mean: # si esta entre el minimo y la media ponme B
                
                f[capa][fila][col] = 'B'
                
                
            elif d_mean == d[capa][fila][col]: # si es la media ponme C en f
                
                f[capa][fila][col] = 'C'
                
                
            elif d_mean < d[capa][fila][col] < d_max: # si esta entre la media y el maximo ponme D
                
                f[capa][fila][col] = 'D'
                
                
            elif d_max == d[capa][fila][col]: # si es el maximo ponme E en f
                
                f[capa][fila][col] = 'E'

In [54]:
f

array([[['B', 'B', 'D', 'D', 'B'],
        ['B', 'B', 'B', 'D', 'A'],
        ['D', 'D', 'B', 'B', 'D']],

       [['B', 'B', 'B', 'D', 'B'],
        ['D', 'D', 'B', 'D', 'B'],
        ['B', 'E', 'D', 'D', 'D']]], dtype='<U32')