# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.__version__)

1.26.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1

a = np.random.random((2, 3, 5)) # 2 depth dimensions, 3 rows, 5 columns
print(a)

[[[0.02979186 0.46929764 0.19613592 0.91514736 0.54193985]
  [0.88030374 0.24241927 0.09518298 0.10672968 0.90031826]
  [0.70714432 0.17127738 0.67840247 0.01753401 0.86967596]]

 [[0.9272832  0.6052259  0.34421499 0.31868377 0.66842281]
  [0.72658903 0.12022482 0.90381248 0.22819196 0.21517867]
  [0.78803484 0.67654768 0.19859095 0.29876649 0.35485926]]]


In [5]:
# Method 2
a1 = np.random.random((3,2,5)).reshape(2,3,5)
print(a1)


[[[0.18792701 0.64743331 0.82439014 0.59699493 0.95771677]
  [0.21126777 0.87645846 0.22386213 0.7486501  0.24924932]
  [0.6100611  0.45099302 0.2239296  0.37952269 0.90101964]]

 [[0.68153429 0.91543207 0.27483665 0.30236765 0.89839769]
  [0.9585053  0.23410927 0.21782275 0.00963436 0.58650893]
  [0.87107231 0.46831513 0.29761557 0.53115743 0.65174375]]]


In [6]:
# Method 3
a2 = np.random.random((5,2,3)).reshape(2,3,5)
print(a2)

[[[0.51862812 0.75356282 0.30475473 0.25346314 0.43042288]
  [0.8410534  0.42241519 0.86116164 0.10515101 0.32592852]
  [0.0129384  0.33429186 0.29103169 0.31683938 0.36599611]]

 [[0.51336816 0.42260056 0.96384839 0.3907078  0.47374043]
  [0.72292501 0.08225426 0.5337485  0.43499495 0.12260219]
  [0.32702764 0.30094805 0.62182955 0.09438053 0.95068823]]]


In [7]:
np.random.rand(2,3,5)

array([[[0.1038725 , 0.80880801, 0.61484323, 0.80774791, 0.4245202 ],
        [0.018946  , 0.02661383, 0.2642545 , 0.98989393, 0.88948144],
        [0.76904304, 0.95377895, 0.81323465, 0.04839447, 0.97514456]],

       [[0.34031921, 0.71565945, 0.87674889, 0.60033331, 0.72021361],
        [0.57934085, 0.38513618, 0.88428459, 0.64261253, 0.20610801],
        [0.37821756, 0.31328055, 0.5763612 , 0.88370628, 0.10367031]]])

In [8]:
np.random.random_sample((2,3,5))

array([[[0.16778907, 0.92296763, 0.84654025, 0.26677143, 0.5556172 ],
        [0.76019107, 0.41354919, 0.74158795, 0.9919203 , 0.3964976 ],
        [0.11429848, 0.2107982 , 0.04183042, 0.93817297, 0.39670263]],

       [[0.02291826, 0.02039401, 0.20303736, 0.84732782, 0.21575552],
        [0.88228829, 0.81008203, 0.0077775 , 0.87996791, 0.27533304],
        [0.71787869, 0.98222909, 0.2422362 , 0.55263611, 0.67547509]]])

#### 4. Print *a*.


In [9]:
# your code here
print(a)

[[[0.02979186 0.46929764 0.19613592 0.91514736 0.54193985]
  [0.88030374 0.24241927 0.09518298 0.10672968 0.90031826]
  [0.70714432 0.17127738 0.67840247 0.01753401 0.86967596]]

 [[0.9272832  0.6052259  0.34421499 0.31868377 0.66842281]
  [0.72658903 0.12022482 0.90381248 0.22819196 0.21517867]
  [0.78803484 0.67654768 0.19859095 0.29876649 0.35485926]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [10]:
# your code here
b = np.ones((5,2,3))


#### 6. Print *b*.


In [11]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [12]:
# your code 
a.size

30

In [13]:
b.size # a and b have the same size but different shape 

30

In [14]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [15]:
# your answer here
a+b # a and b have different shapes so we can not sum them 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [16]:
# your code here
c = b.transpose(1,2,0)

In [17]:
c.shape

(2, 3, 5)

In [18]:
a.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [19]:
# your code/answer here
d = a+c # now a and c have the same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [20]:
# your code/answer here
print(a)

[[[0.02979186 0.46929764 0.19613592 0.91514736 0.54193985]
  [0.88030374 0.24241927 0.09518298 0.10672968 0.90031826]
  [0.70714432 0.17127738 0.67840247 0.01753401 0.86967596]]

 [[0.9272832  0.6052259  0.34421499 0.31868377 0.66842281]
  [0.72658903 0.12022482 0.90381248 0.22819196 0.21517867]
  [0.78803484 0.67654768 0.19859095 0.29876649 0.35485926]]]


In [21]:
print(d) # the elements of d matriz are one more than the elements of a

[[[1.02979186 1.46929764 1.19613592 1.91514736 1.54193985]
  [1.88030374 1.24241927 1.09518298 1.10672968 1.90031826]
  [1.70714432 1.17127738 1.67840247 1.01753401 1.86967596]]

 [[1.9272832  1.6052259  1.34421499 1.31868377 1.66842281]
  [1.72658903 1.12022482 1.90381248 1.22819196 1.21517867]
  [1.78803484 1.67654768 1.19859095 1.29876649 1.35485926]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [22]:
# your code here
e = a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [23]:
# your code/answer here
e.shape

(2, 3, 5)

In [24]:
a.shape # a and e have the same size and shape but the elements (value of the elements) of these arrays are not the same 

(2, 3, 5)

In [25]:
a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [26]:
# your code here
d_max = d.max()
print(d_max)

1.9272831979972298


In [27]:
d_min = d.min()
print(d_min)

1.0175340056912738


In [28]:
d_mean = d.mean()
print(d_mean)

1.4731975848929402


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [29]:
# your code here
f = np.empty_like(d)
print(f)

[[[1.02979186 1.46929764 1.19613592 1.91514736 1.54193985]
  [1.88030374 1.24241927 1.09518298 1.10672968 1.90031826]
  [1.70714432 1.17127738 1.67840247 1.01753401 1.86967596]]

 [[1.9272832  1.6052259  1.34421499 1.31868377 1.66842281]
  [1.72658903 1.12022482 1.90381248 1.22819196 1.21517867]
  [1.78803484 1.67654768 1.19859095 1.29876649 1.35485926]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [34]:
%%time
for capa in range(f.shape[0]): # 2 dimesions
    for fila in range(f.shape[1]): # 3 rows 
        for col in range(f.shape[2]): # 5 columns
            
            if d_min == d[capa][fila][col]: # if it is the min value, put 0 in f matrix
                
                f[capa][fila][col] = 0
                
            
            elif d_min < d[capa][fila][col] < d_mean: # if it is between mean value and min value, put 25 in f matrix
                
                f[capa][fila][col] = 25
                
                
            elif d_mean == d[capa][fila][col]: # if it is mean value put 50 in f matrix
                
                f[capa][fila][col] = 50
                
                
            elif d_mean < d[capa][fila][col] < d_max: # if it is value between mean value and max value put 75 in f matrix
                
                f[capa][fila][col] = 75
                
                
            elif d_max == d[capa][fila][col]: # if it is max value put 100 in f matrix
                
                f[capa][fila][col] = 100
        

CPU times: user 137 µs, sys: 22 µs, total: 159 µs
Wall time: 225 µs


In [32]:
print(f)

[[[ 25.  25.  25.  75.  75.]
  [ 75.  25.  25.  25.  75.]
  [ 75.  25.  75.   0.  75.]]

 [[100.  75.  25.  25.  75.]
  [ 75.  25.  75.  25.  25.]
  [ 75.  75.  25.  25.  25.]]]


In [55]:
%%time
np.where ((d > d_min) & (d<d_mean), 25, 
        np.where(d == d_mean, 50, 
                np.where(d == d_min,0, 
                        np.where(d == d_max, 100,75))))

CPU times: user 70 µs, sys: 1 µs, total: 71 µs
Wall time: 87 µs


array([[[ 25,  25,  25,  75,  75],
        [ 75,  25,  25,  25,  75],
        [ 75,  25,  75,   0,  75]],

       [[100,  75,  25,  25,  75],
        [ 75,  25,  75,  25,  25],
        [ 75,  75,  25,  25,  25]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [57]:
# your code here
print(d)

[[[1.02979186 1.46929764 1.19613592 1.91514736 1.54193985]
  [1.88030374 1.24241927 1.09518298 1.10672968 1.90031826]
  [1.70714432 1.17127738 1.67840247 1.01753401 1.86967596]]

 [[1.9272832  1.6052259  1.34421499 1.31868377 1.66842281]
  [1.72658903 1.12022482 1.90381248 1.22819196 1.21517867]
  [1.78803484 1.67654768 1.19859095 1.29876649 1.35485926]]]


In [58]:
print(f)

[[[ 25.  25.  25.  75.  75.]
  [ 75.  25.  25.  25.  75.]
  [ 75.  25.  75.   0.  75.]]

 [[100.  75.  25.  25.  75.]
  [ 75.  25.  75.  25.  25.]
  [ 75.  75.  25.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [59]:
# your code here
letras = np.where(f == 0, 'A', np.where (f == 25, 'B', np.where(f==50, 'C',np.where(f==75,'D', 'E'))))
print(letras)

[[['B' 'B' 'B' 'D' 'D']
  ['D' 'B' 'B' 'B' 'D']
  ['D' 'B' 'D' 'A' 'D']]

 [['E' 'D' 'B' 'B' 'D']
  ['D' 'B' 'D' 'B' 'B']
  ['D' 'D' 'B' 'B' 'B']]]
