# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np
import random

#### 2. Print your NumPy version.

In [3]:
# your code here

print(np. __version__)

1.24.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1

a = np.random.random((2,3,5))
a

array([[[0.75739342, 0.26418047, 0.99671104, 0.21117798, 0.69922143],
        [0.42300584, 0.05242275, 0.18377073, 0.36951406, 0.65078977],
        [0.46904956, 0.0265511 , 0.64089867, 0.00855946, 0.60375691]],

       [[0.17881325, 0.95824525, 0.49756177, 0.56489729, 0.05353046],
        [0.84102748, 0.43272148, 0.39062201, 0.02109715, 0.98815687],
        [0.72917875, 0.81946212, 0.23606386, 0.69313858, 0.95840508]]])

In [7]:
# Method 2
a = np.empty([2,3,5])
a

array([[[0.64839578, 0.820679  , 0.62817598, 0.17471747, 0.73785311],
        [0.48718207, 0.31776186, 0.02281954, 0.77307454, 0.65072927],
        [0.58397373, 0.37274632, 0.09463181, 0.06674595, 0.13039797]],

       [[0.98735773, 0.87834638, 0.26321774, 0.73267062, 0.43102513],
        [0.68462994, 0.5052911 , 0.79427351, 0.07407954, 0.88708993],
        [0.03539385, 0.0026381 , 0.26197845, 0.54201966, 0.1519543 ]]])

In [6]:
# Method 3

a = np.random.rand(2,3,5)
a

array([[[0.64839578, 0.820679  , 0.62817598, 0.17471747, 0.73785311],
        [0.48718207, 0.31776186, 0.02281954, 0.77307454, 0.65072927],
        [0.58397373, 0.37274632, 0.09463181, 0.06674595, 0.13039797]],

       [[0.98735773, 0.87834638, 0.26321774, 0.73267062, 0.43102513],
        [0.68462994, 0.5052911 , 0.79427351, 0.07407954, 0.88708993],
        [0.03539385, 0.0026381 , 0.26197845, 0.54201966, 0.1519543 ]]])

#### 4. Print *a*.


In [47]:
# your code here
print(a)

[[[0.25257422 0.40699415 0.65792402 0.88551744 0.04734188]
  [0.07145876 0.08724301 0.0647137  0.19005353 0.61636487]
  [0.91537744 0.32441123 0.77884074 0.8988341  0.97654085]]

 [[0.40076652 0.2488312  0.40386845 0.82322351 0.65130558]
  [0.07711254 0.57371374 0.78716392 0.17622022 0.443459  ]
  [0.97434117 0.0561761  0.03070605 0.82994607 0.76457672]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [56]:
# your code here
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [57]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [61]:
# your code here
np.size(a)

30

In [62]:
np.size(b)

# yes, they are the same size

30

#### 8. Are you able to add *a* and *b*? Why or why not?


In [8]:
# your answer here

np.add(a, b)

# You can´t and it gives you this error back "ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3)" because the shapes doesn´t match

NameError: name 'b' is not defined

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [79]:
# your code here

c = np.transpose(b)
c = np.reshape(c, (2, 3,5), order='F')
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
c = b.transpose(3,2,0)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [78]:
# your code/answer here
d = np.add(a,c)
d

#It works because they are the same size

array([[[1.25257422, 1.40699415, 1.65792402, 1.88551744, 1.04734188],
        [1.07145876, 1.08724301, 1.0647137 , 1.19005353, 1.61636487],
        [1.91537744, 1.32441123, 1.77884074, 1.8988341 , 1.97654085]],

       [[1.40076652, 1.2488312 , 1.40386845, 1.82322351, 1.65130558],
        [1.07711254, 1.57371374, 1.78716392, 1.17622022, 1.443459  ],
        [1.97434117, 1.0561761 , 1.03070605, 1.82994607, 1.76457672]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [80]:
# your code/answer here
print("a: ",a)
print("d: ",d)

a:  [[[0.25257422 0.40699415 0.65792402 0.88551744 0.04734188]
  [0.07145876 0.08724301 0.0647137  0.19005353 0.61636487]
  [0.91537744 0.32441123 0.77884074 0.8988341  0.97654085]]

 [[0.40076652 0.2488312  0.40386845 0.82322351 0.65130558]
  [0.07711254 0.57371374 0.78716392 0.17622022 0.443459  ]
  [0.97434117 0.0561761  0.03070605 0.82994607 0.76457672]]]
d:  [[[1.25257422 1.40699415 1.65792402 1.88551744 1.04734188]
  [1.07145876 1.08724301 1.0647137  1.19005353 1.61636487]
  [1.91537744 1.32441123 1.77884074 1.8988341  1.97654085]]

 [[1.40076652 1.2488312  1.40386845 1.82322351 1.65130558]
  [1.07711254 1.57371374 1.78716392 1.17622022 1.443459  ]
  [1.97434117 1.0561761  1.03070605 1.82994607 1.76457672]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [81]:
# your code here
e = np.multiply(a,c)
e

array([[[0.25257422, 0.40699415, 0.65792402, 0.88551744, 0.04734188],
        [0.07145876, 0.08724301, 0.0647137 , 0.19005353, 0.61636487],
        [0.91537744, 0.32441123, 0.77884074, 0.8988341 , 0.97654085]],

       [[0.40076652, 0.2488312 , 0.40386845, 0.82322351, 0.65130558],
        [0.07711254, 0.57371374, 0.78716392, 0.17622022, 0.443459  ],
        [0.97434117, 0.0561761 , 0.03070605, 0.82994607, 0.76457672]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [84]:
print("e; ",e)
print("a: ",a)

#They are not equal

e;  [[[0.25257422 0.40699415 0.65792402 0.88551744 0.04734188]
  [0.07145876 0.08724301 0.0647137  0.19005353 0.61636487]
  [0.91537744 0.32441123 0.77884074 0.8988341  0.97654085]]

 [[0.40076652 0.2488312  0.40386845 0.82322351 0.65130558]
  [0.07711254 0.57371374 0.78716392 0.17622022 0.443459  ]
  [0.97434117 0.0561761  0.03070605 0.82994607 0.76457672]]]
a:  [[[0.25257422 0.40699415 0.65792402 0.88551744 0.04734188]
  [0.07145876 0.08724301 0.0647137  0.19005353 0.61636487]
  [0.91537744 0.32441123 0.77884074 0.8988341  0.97654085]]

 [[0.40076652 0.2488312  0.40386845 0.82322351 0.65130558]
  [0.07711254 0.57371374 0.78716392 0.17622022 0.443459  ]
  [0.97434117 0.0561761  0.03070605 0.82994607 0.76457672]]]


In [83]:
# your code/answer here
if e.all == a.all:
    print("they are equal")
else:
    print("they are not equal")

they are not equal


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

NameError: name 'd' is not defined

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty([2,3,5])
f

array([[[0.64839578, 0.820679  , 0.62817598, 0.17471747, 0.73785311],
        [0.48718207, 0.31776186, 0.02281954, 0.77307454, 0.65072927],
        [0.58397373, 0.37274632, 0.09463181, 0.06674595, 0.13039797]],

       [[0.98735773, 0.87834638, 0.26321774, 0.73267062, 0.43102513],
        [0.68462994, 0.5052911 , 0.79427351, 0.07407954, 0.88708993],
        [0.03539385, 0.0026381 , 0.26197845, 0.54201966, 0.1519543 ]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [110]:
# your code here
f[(d_min < d) & (d < d_mean)] = 25
f[(d_mean < d) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

        

[[[0.25257422 0.40699415 0.65792402 0.88551744 0.04734188]
  [0.07145876 0.08724301 0.0647137  0.19005353 0.61636487]
  [0.91537744 0.32441123 0.77884074 0.8988341  0.97654085]]

 [[0.40076652 0.2488312  0.40386845 0.82322351 0.65130558]
  [0.07711254 0.57371374 0.78716392 0.17622022 0.443459  ]
  [0.97434117 0.0561761  0.03070605 0.82994607 0.76457672]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [112]:
# your code here
print("d: ", d)
print("f: ", f)

d:  [[[1.25257422 1.40699415 1.65792402 1.88551744 1.04734188]
  [1.07145876 1.08724301 1.0647137  1.19005353 1.61636487]
  [1.91537744 1.32441123 1.77884074 1.8988341  1.97654085]]

 [[1.40076652 1.2488312  1.40386845 1.82322351 1.65130558]
  [1.07711254 1.57371374 1.78716392 1.17622022 1.443459  ]
  [1.97434117 1.0561761  1.03070605 1.82994607 1.76457672]]]
f:  [[[ 25.  25.  75.  75.  25.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  25.  75.  75. 100.]]

 [[ 25.  25.  25.  75.  75.]
  [ 25.  75.  75.  25.  25.]
  [ 75.  25.   0.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [115]:
# your code here

f[(d.min < d) & (d < d.mean)] = "B"
f[(d.min < d) & (d < d.max)] = "D"
f[d.mean == d] = "C"
f[d.min == d] = "A"
f[d.max == d] = "E"

print(f)

ValueError: could not convert string to float: 'B'